version: "3"
services:
  web:
    build: .
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
     - "3000:3000"
  mariadb:
    image: mariadb
    restart: always
    volumes:
     - ./init:/docker-entrypoint-initdb.d
    env_file:
      - ../mariadb.env
    ports:
      - 3306:3306
