version: "3"
services:
  web:
    build: .
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
    env_file: ../phprest.env
    ports:
     - "3000:3000"
  api:
    image: rlkamradt/phprest:latest
    env_file:
      - ../phprest.env
    ports:
      - 8001:8000
  mariadb:
    image: mariadb
    restart: always
    volumes:
     - ./init:/docker-entrypoint-initdb.d
    env_file:
      - ../phpapp.env
    ports:
      - 3306:3306
